[package]
name = "rustvault"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
mongodb = "3.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
tower-http = { version = "0.5", features = ["cors"] }

dotenvy = "0.15"
